### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUs1MlY2TVoxUUdKOVMyR1BZMjBCQTlYMCIsInNlc3Npb25JZCI6IjAxSzUzRTNRTVpUWldYTlpNVFlBTldIOTJGIiwiZXhwIjoxNzU3ODMxNzMxfQ.jvKLv9ZT8kXJYLLSiPzJUadd0X_rUCeX9ExV916uMQY
@refreshToken = 01K53E3QMYC0YANCP7ZE6ENQ84
@userId = 01K52V6MZ1QGJ9S2GPY20BA9X0
@host = http://localhost:1234

### Actualizar perfil (PATCH)
PATCH {{host}}/api/v1/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Sammy",
  "lastName": "Gonzalez",
  "country": "Dominican Republic",
  "city": "Santo Domingo",
  "bio": "Desarrollador fullstack",
  "avatar": "https://example.com/avatar.png",
  "languages": ["TypeScript", "C#"],
  "frameworks": ["Blazor", "HonoJS"],
  "tools": ["VSCode", "Git"]
}

### Retrieve profile (GET)
GET {{host}}/api/v1/profile/me
Authorization: Bearer {{token}}

### Retrieve profile by userId (GET)
GET {{host}}/api/v1/profile/{{userId}}
Authorization: Bearer {{token}}
